### PR TITLE
fix: custom kube config

### LINKED ISSUE #479: invalid kubernetes configuration kills config-db
if you pass a non existing kube config path to ketall, it kills the process

```go
func KetAll(ketallOptions *options.KetallOptions) []*unstructured.Unstructured {
	all, err := client.GetAllServerResources(ketallOptions)
	if err != nil {
		klog.Fatal(err)
	}
```

### PR DESCRIPTION
**Pull request by adityathebe**
* When a custom config was passed, it wasn't used in the discovery client and as a restmapper
* fix deadlock by setting a default value for maxinflight

resolves: https://github.com/flanksource/config-db/issues/479

### CODE REVIEW

File: options/options.go [hunk 1]
```diff
@@ -51,8 +63,51 @@ func (t *KetAllConfigFlags) ToRESTConfig() (*rest.Config, error) {
...
+		cacheDir := os.TempDir()
+		httpCacheDir := filepath.Join(cacheDir, "http")
+		discoveryCacheDir := computeDiscoverCacheDir(filepath.Join(cacheDir, "discovery"), config.Host)
+		return diskcached.NewCachedDiscoveryClientForConfig(config, discoveryCacheDir, httpCacheDir, time.Duration(6*time.Hour))
+	}
+
+	return t.ConfigFlags.ToDiscoveryClient()
+}
+
+// Copyright 2018 The Kubernetes Authors.
```
Comment (adityathebe) [inline options/options.go:93]: @moshloop not exactly sure how to attribute the original authors.
